version: '3.9'

services:
  pgadmin:
    image: 'dpage/pgadmin4'
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      - 'PGADMIN_DEFAULT_EMAIL=nimon@42paris.fr'
      - 'PGADMIN_DEFAULT_PASSWORD=transcendence'
    networks:
      - backend
#TODO: add persistent storage

  backend:
    build:
      context: ./nestjs-docker
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - backend
    volumes:
      - ./nestjs-docker:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - pgadmin

  frontend:
    build:
      context: ./vuejs-docker
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
      # - 8081:8081
    networks:
      - backend
    volumes:
      - ./vuejs-docker:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=development
      - VUE_APP_BACKEND_URL=http://backend:3000
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    depends_on:
      - pgadmin
      - backend
networks:
  backend:
