version: '3.9'

services:
  # postgres:
  #   image: postgres:latest
  #   env_file:
  #     - docker.env
  #   restart: unless-stopped
  #   ports : 
  #     - "5432:5432"
  #   volumes :
  #     - /data/postgres:/data/postgres
  #   networks :
  #     - backend

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - 5050:80
    volumes :
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - backend
    # depends_on:
    #   - postgres

  # backend:
  #   build:
  #     context: ./nestjs-docker
  #     target: development
  #     dockerfile: ./Dockerfile
  #   command: npm run start:dev
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - backend
  #   volumes:
  #     - ./nestjs-docker:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  frontend:
    build:
      context: ./vuejs-docker
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./vuejs-docker:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file:
      - docker.env
    restart: unless-stopped
    depends_on:
      - pgadmin
    #   - postgres
    #   - backend
networks:
  backend:
