version: '3.9'

services:
  # postgres:
  #   image : postgres:latest
  #   env_file:
  #     - docker.env
  #   restart: unless-stopped
  #   ports : 
  #     - "5432:5432"
  #   networks :
  #     - backend

  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   restart: unless-stopped
  #   env_file:
  #     - docker.env
  #   ports:
  #     - 5050:80
  #   networks:
  #     - backend
  #   depends_on:
  #     - postgres

  # backend:
  #   build:
  #     context: ./docker
  #     dockerfile: ./backend.dockerfile
  #   ports:
  #     - 3000:3000
  #     - 9229:9229
  #   networks:
  #     - backend
  #   volumes:
  #     - ./backend:/app
  #   restart: unless-stopped
  #   depends_on:
  #     - postgres

  frontend:
    build:
      context: ./docker
      dockerfile: ./frontend.dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./frontend:/app
    env_file:
      - docker.env
    restart: unless-stopped
    # depends_on:
      # - postgres
      # - backend
networks:
  backend:
